### ISSUE TITLE
`ind_5` Winner's share doubts writing it down!

### ISSUE THREAD

**Issue by giuliogcantone** [CORE-forge/coresoi#12]
I am asked to code this indicator.

There are a bunch of problems with this indicator:

* In the documentation this is an index of pre-post concentration. Correctly, this is a pre-post Gini (or any index of the bounded entropy family).
* Concentration is not the same thing as "Winner's shares" (e.g. of a market).
* Gini makes sense only as an indicator for the agency and **not** for the Winner. It makes no sense to flag a company as suspicious of corruption if after a crisis it wins ONLY in some Agencies while before it used to win in many more. Think about a urn process where I draw 5 blue balls and 5 red balls. My concentration is 0. Then I add a selection bias in the process and I draw 1 blue ball and 5 red balls. My concentration raises, but I am actually winning less overall, so how can I be accused of corruption???
It makes sense only for agencies that both raised their frequency of wins and concentration.
* For Agencies it makes sense because they actually control who wins the bid, so they are _**imputable**_ of the selection bias. Even if they reduced the number of balls in the stochastic process, why does one color seems to keep being drawn more?

Proposal:

* Rename it, while keeping the explanation that mentions Gini itself.
* Simplify this just as a test on Agencies only, on pre-post differences in Gini, which I guess is in line with @simonedelsa original proposal. Simone's code does much more passages so I want to be sure my understanding is correct.

Gini is not a proportion, do we need a specific test for pre-post Gini? Please indicate me the correct test for pre-post Gini, which is still the difference between the 2 sample estimates, not 2 distributions (so, I am confused about mentioning KS test).

P.S. I know very well that this discussion has been made at least 3 times but I think it was never put down written with explicit considerations.

**Comment by simonedelsa** [comment]
Thanks @giuliogcantone for this issue. 

I'm totally agree with you for each point and with your proposals. The indicator explanation in CORE deliverable 4.3 needs to be adjusted according to your comments (I'm working on it, as other parts need adjustments as well). 

Currently, I am not sure on how testing the pre-post for this indicator, but no KS test and no Barnard for sure! We can discuss about it on next Thurdsay at 9.30.

**Comment by NiccoloSalvini** [comment]
I implemented the indicator like @giuliogcantone suggested in f9072e75142269dc33085019a966837cc320f46a.
