### ISSUE TITLE
`ind_9` Caused by error in `t.test.default()`: ! not enough 'x' observations

### ISSUE THREAD

**Issue by NiccoloSalvini** [CORE-forge/coresoi#18]
## installation 

first install dev branch `ind_9` with commands:

```r

remotes::install_github(c("CORE-forge/coresoi@ind_9"))
```

##  `{reprex}`

I tried many times but that seems to not work in any case. Do you know why?

``` r
library(coresoi)
ind_9(
 data = mock_data_core,
 publication_date = data_pubblicazione,
 stat_unit = cf_amministrazione_appaltante,
 cpv = cod_cpv,
 eff_start =data_inizio_effettiva,
 eff_end = data_effettiva_ultimazione,
 emergency_name = "coronavirus"
)
#> Error in `dplyr::mutate()`:
#> ℹ In argument: `ttest = ...$p.value`.
#> ℹ In group 1: `cf_amministrazione_appaltante = "00040720070"`.
#> Caused by error in `t.test.default()`:
#> ! not enough 'x' observations
```
<sup>Created on 2023-02-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by simonedelsa** [comment]
Yes, I was aware of this. However, the following code doesn't work for me:

*remotes::install_github(c("CORE-forge/coresoi@ind_9"))*

Anyway, I can discuss on this issue directly tomorrow at our scheduled meeting.
