### ISSUE TITLE
add `composite` indicator

### ISSUE THREAD

**Issue by NiccoloSalvini** [CORE-forge/coresoi#19]
## context

we now want to add the composition of all indicators which synthesize the risk associated to the single `stat_unit`. We may want to imagine the composition  result as a point projected into a _n_ multidimensional space where dimensions are indicators and `f()` i.e. the composition function a way to perturbate those dimensions.
Since composition should have **a single target**, meaning it can't be compute for both `cf_amministrazione_appaltante` and `denominazione` i.e. (winner's business name) we need to have a function which takes as an argument which is the target.
Moreover some of them are exclusively calculated on either `cf_amministrazione_appaltante` or `denominazione` which reduces the problem to:

- compute conditional composition based on target being `cf_amministrazione_appaltante` or `descrizione` (set of indicators **1**, **2** and **3** on first one and **4**, **5** and **6** for second one)

## maybe the case of

1. within `R/composite.R`
...

**Comment by simonedelsa** [comment]
Ok @NiccoloSalvini. It is possible that a contracting authority or a winner company has NA as final value for a specific indicator. But this is not a problem, we can merge all the indicators for each statistical unit using a *full join* across each indicator data matrix. I suspect that we'll have many missing values, especially for winners. Let's see what happens!

**Comment by NiccoloSalvini** [comment]
solved in 52f4296 and following

**Comment by NiccoloSalvini** [comment]
solved in 52f4296 and following!
