### ISSUE TITLE
`ind_5_bis()` generates pre/post proportions leading to 2 values per `stat_unit` 

### ISSUE THREAD

**Issue by NiccoloSalvini** [CORE-forge/coresoi#5]
## context

we are having in the whole package 1 indicator value per stat_unit. In this case we are calculcating 2, one indicator value for **pre** and 1 for **post**.

## reprex 

```
library(coresoi)
coresoi::ind_5_bis(
data = mock_data_core, 
publication_date = data_pubblicazione, 
cpv = cod_cpv,
emergency_name = "coronavirus",
cpv_division = "33", stat_unit = provincia
)
```

which leads to a **224** by 12 instead of 112 by 12. As a matter of fact we have for "Agrigento" (1st and 2nd rows) both **0.65** and **0.51**.

```
# A tibble: 224 × 12
   indicator…¹ indic…² indic…³ aggre…⁴ aggre…⁵ aggre…⁶ emerg…⁷ emerg…⁸
         <dbl> <chr>     <dbl> <fct>   <chr>   <chr>     <int> <chr>  
 1         5.1 Awarde…   0.654 AGRIGE… ISTAT1  provin…       1 Corona…
 2         5.1 Awarde…   0.516 AGRIGE… ISTAT1  provin…       1 Corona…
 3         5.1 Awarde…   0.698 ALESSA… ISTAT1  provin…       1 Corona…
 4         5.1 Awarde…   0.877 ALESSA… ISTAT1  provin…       1 Corona…
 5         5.1 Awarde…   0.935 ANCONA  ISTAT1  provin…       1 Corona…
 6         5.1 Awarde…   0.966 ANCONA  ISTAT1  provin…       1 Corona…
 7         5.1 Awarde…   0.971 AREZZO  ISTAT1  provin…       1 Corona…
 8         5.1 Awarde…   0.977 AREZZO  ISTAT1  provin…       1 Corona…
 9         5.1 Awarde…   0.926 ASCOLI… ISTAT1  provin…       1 Corona…
10         5.1 Awarde…   0.939 ASCOLI… ISTAT1  provin…       1 Corona…
```

How do we handle that? We may want to compare two proportions with a test and have the pvalue being the indicator output?

**Comment by giuliogcantone** [comment]
Personally, I would not employ p-value as a metric.

I would employ a normalised difference post - pre as a metric.

e.g.

`
if (p < alpha) {qlogis(POST_ind_05) - qlogis(PRE_ind_05)}
else {0}
`

But this is just the first thing that came into my mind. I believe this is a model-coherent metric.
Probably you want to check [this](https://en.wikipedia.org/wiki/Cohen%27s_h) instead; easier to interpret since it allows to make comparisons across indicators, like "ind_x is significantly higher than ind_y". As much as I remember, you can treat Cohen's $h$ as sample means (fixed a stat unit, e.g. Agrigento) and then NHST across indicators should be easy. Which is nice propriety.

**Comment by NiccoloSalvini** [comment]
pvalues are also counterintuitive measure, the bigger they are, the worst they are. We may think to have it as a weight for composing the synthetic indicator. 

I pretty much agree on everything you said and I really like your Cohen's $h$ proposal. I would straight discuss the implementation with @simonedelsa and the other @CORE-forge/statistics team (i.e. Ranalli + Gnaldi). That seems intuitive and relatively simple to implement. I briefly scrolled prop tests and I couldn't find anything better than that.

I also briefly skimmed though the software and I found that package `pwr` does exactly that.

```
library(pwr)
h<-ES.h(0.5,0.4)
h
pwr.p.test(h=h,n=60,sig.level=0.05,alternative="two.sided")
```

[From this stackexchange](https://stats.stackexchange.com/questions/80082/confidence-intervals-for-cohens-h-effect-size) there's also a native implementation which avoids imports. However I found `pwr` implementation weird. Why do I have to pass `ES.h()` to proportions to then perform with `pwr.p.test` the test instead of doing in 1 step.

```
cohens_h = function( prop_1, prop_2, n1, n2, ci = 0.95 ){
    x1 = asin(sign(prop_1) * sqrt(abs(prop_1)))
    x2 = asin(sign(prop_2) * sqrt(abs(prop_2)))
    es = x1 - x2
    se = sqrt(0.25 * (1 / n1 + 1 / n2 ))
    ci_diff = qnorm(1 - (1-ci) / 2) * se
    return( c( h = es*2, h_low = (es-ci_diff)*2, h_upp = (es+ci_diff)*2 ) )
}
``` 

having 

```
#         h      h_low      h_upp 
# -0.5157784 -0.6946978 -0.3368590 
```

**Comment by giuliogcantone** [comment]
Check this Wikipedia article on the summarisation of p-values:

https://en.wikipedia.org/wiki/Fisher%27s_method
