### ISSUE TITLE
From `regione` and `cf_amministrazione_appaltante` to NUTS.

### ISSUE THREAD

**Issue by NiccoloSalvini** [CORE-forge/coresoi#6]
##  context

Indicators schema needs to generate also `aggregation_id` which can be instead of an int ranging from 1 to 20, their [NUTS code](https://www.europarl.europa.eu/factsheets/it/sheet/99/nomenclatura-comune-delle-unita-territoriali-statistiche-nuts-). This should happen for each  geographical `aggregation_type` level i.e. provincia e comune, but also for `cf_amministrazione_appaltante` which has not really a geographical level (I found a file with C.A. registry information, me may use it to locate each `cf_amministrazione_appaltante` and then trace back its geo).

## current behavior

not accounted.

## expected behavior

- option **1**: manually define a function that maps each region (province and municipality) to its NUTS.

```r
get_nuts_code <- function(region_name) {
  # get NUTS code for a given region name
  # regionName: string of the region name
  # returns: string of the NUTS code

  # dictionary of regions and their NUTS codes
  region_nuts_dict <- list(
    "Abruzzo" = "ITC1",
    "Basilicata" = "ITC2",
    "Calabria" = "ITC3",
    "Campania" = "ITC4",
    "Emilia-Romagna" = "ITC5",
    "Friuli-Venezia Giulia" = "ITC6",
    "Lazio" = "ITC7",
    "Liguria" = "ITC8",
    "Lombardia" = "ITC9",
    "Marche" = "ITD1",
    "Molise" = "ITD2",
    "Piemonte" = "ITD3",
    "Puglia" = "ITD4",
    "Sardegna" = "ITE1",
    "Sicilia" = "ITE2",
    "Toscana" = 	"ITE3",
    "Trentino-Alto Adige/Südtirol" =	"ITE4", 																			 
    "Umbria" = 	"ITE5", 			  
    "Valle d'Aosta/Vallée d'Aoste" = 	"ITE6", 	  
    "Veneto" = 	"ITE7")

# return the NUTS code for the given region name, if it exists in the dictionary. Otherwise, returns NULL.  
  return(region_nuts_dict[region_name]) 
}
```

and then for provinces and municipalities (🤣)

- option **2**. have a data file to refer to (I found [this .csv](https://www.istat.it/storage/codici-unita-amministrative/Elenco-comuni-italiani.csv)) and then we may vlookup. This is for region, we may abstractize it for each aggregation level.

```r
vlookup_geo_entity <- function(region) {
  # read in the data from the csv file
  nuts_data <- read.csv("<path_to_csv>")

  # find the row with the matching region name
  row <- which(nuts_data$region == region)

  # return the NUTS code for that row
  return(nuts_data$NUTS[row])

```

**Comment by giuliogcantone** [comment]
Is there a reason to use base R instead of dplyer's joins?

**Comment by NiccoloSalvini** [comment]
This needs to be handled on the backedn of the application, in the database. Data should come with these information and the package should only be able to call the right column!
