### ISSUE TITLE
Renaming indicators

### ISSUE THREAD

**Issue by giuliogcantone** [CORE-forge/coresoi#7]
New  - Object - Old number - Done?
1 - Winning rate across the crisis - 1 - Y
2 - Awarded economic value across the crisis - 2 - Y
**3 - Economic deviation across the crisis - N - N**
**4 - Length deviation across the crisis - 4 - N**
**5 - Winner's share of issuer's contract across the crisis - N - N** 
6 - Communication default across the crisis - 5 - Y
7 - One-shot opportunistic companies over the crisis - 3 - Y
8 - Pre-existing contracts modified after the crisis - 6 - Y
**9 - Lengthy contracts - N - N**
10 - Inconsistent companies across the crisis - 7 - N
11 - Inconsistent contract objects across the crisis - N - N
12 - Small companies winning big contracts across the crisis - 9  N
13 - Direct contracts to anonymous companies across the crisis - N - N
14 - Companies registered in tax havens - N - N
15 - Companies flagged in the national anti-money laundering alert system - N - N

**Comment by giuliogcantone** [comment]
According to this scheme, we should give priority to complete New Indicators

* 3
* 4
* 5
* 9

@simonedelsa @NiccoloSalvini please give me confirmation that indicators n3 and n4 are not already coded.

n4 is open but empty: https://github.com/CORE-forge/coresoi/blob/main/R/04-lengthy-contract.R

**Comment by NiccoloSalvini** [comment]
Totally agree. Let's  proceed as you highlighted!
